---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-amqpbroker-connection-secret
stringData:
  integrations-broker.url: amqps://amq-ssl-broker-amqp-0-svc.amq7-broker-cluster.svc:5672?transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000
  integrations-broker.username: camel-quarkus-rhoam-webhook-handler-api
  integrations-broker.password: P@ssw0rd
  integrations-broker.pool-max-connections: '1'
  integrations-broker.max-sessions-per-connection: '500'
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-opentracing-endpoint-secret
stringData:
  quarkus.jaeger.endpoint: 'http://jaeger-all-in-one-inmemory-collector.3scale-amp.svc:14268/api/traces'
type: Opaque