---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-amqpbroker-connection-secret
stringData:
  quarkus.qpid-jms.password: "P@ssw0rd"
  quarkus.qpid-jms.url: "amqps://amq-ssl-broker-amqp-0-svc.amq7-broker-cluster.svc:5672?transport.trustAll=true&transport.verifyHost=false&amqp.idleTimeout=120000"
  quarkus.qpid-jms.username: "camel-quarkus-rhoam-webhook-handler-api"
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: quarkus-opentracing-endpoint-secret
stringData:
  quarkus.jaeger.endpoint: "http://jaeger-all-in-one-inmemory-collector.3scale-amp.svc:14268/api/traces"
type: Opaque